# Generated manually to fix import issues
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_excel', models.IntegerField(null=True)),
                ('programa', models.TextField(blank=True, null=True)),
                ('area_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('eje_institucional', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_recurso', models.CharField(blank=True, max_length=255, null=True)),
                ('concentrado_programas', models.CharField(blank=True, max_length=255, null=True)),
                ('capitulo_gasto', models.CharField(blank=True, max_length=100, null=True)),
                ('presupuesto_modificado', models.FloatField(default=0)),
                ('anteproyecto_total', models.FloatField(default=0)),
                ('meta_2025', models.FloatField(default=0)),
                ('meta_2026', models.FloatField(default=0)),
                ('unidad_medida', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_unitario', models.FloatField(default=0)),
                ('proyecto_2025_presupuesto', models.FloatField(blank=True, null=True)),
                ('multianualidad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_obra', models.CharField(blank=True, max_length=255, null=True)),
                ('alcance_territorial', models.TextField(blank=True, null=True)),
                ('fuente_financiamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('etapa_desarrollo', models.CharField(blank=True, max_length=255, null=True)),
                ('complejidad_tecnica', models.IntegerField(default=1)),
                ('impacto_social', models.IntegerField(default=1)),
                ('alineacion_estrategica', models.IntegerField(default=1)),
                ('impacto_social_nivel', models.IntegerField(default=1)),
                ('urgencia', models.IntegerField(default=1)),
                ('viabilidad_ejecucion', models.IntegerField(default=1)),
                ('recursos_disponibles', models.IntegerField(default=1)),
                ('riesgo_nivel', models.IntegerField(default=1)),
                ('dependencias_nivel', models.IntegerField(default=1)),
                ('puntuacion_final', models.FloatField(blank=True, null=True)),
                ('viabilidad_tecnica_semaforo', models.CharField(blank=True, max_length=50, null=True)),
                ('viabilidad_presupuestal_semaforo', models.CharField(blank=True, max_length=50, null=True)),
                ('viabilidad_juridica_semaforo', models.CharField(blank=True, max_length=50, null=True)),
                ('viabilidad_temporal_semaforo', models.CharField(blank=True, max_length=50, null=True)),
                ('viabilidad_administrativa_semaforo', models.CharField(blank=True, max_length=50, null=True)),
                ('alcaldias', models.TextField(blank=True, null=True)),
                ('ubicacion_especifica', models.TextField(blank=True, null=True)),
                ('beneficiarios_directos', models.CharField(blank=True, max_length=255, null=True)),
                ('poblacion_objetivo_num', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio_prog', models.DateField(blank=True, null=True)),
                ('fecha_termino_prog', models.DateField(blank=True, null=True)),
                ('duracion_meses', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_termino_real', models.DateField(blank=True, null=True)),
                ('avance_fisico_pct', models.FloatField(default=0)),
                ('avance_financiero_pct', models.FloatField(default=0)),
                ('estatus_general', models.CharField(blank=True, max_length=255, null=True)),
                ('permisos_requeridos', models.TextField(blank=True, null=True)),
                ('estatus_permisos', models.TextField(blank=True, null=True)),
                ('requisitos_especificos', models.TextField(blank=True, null=True)),
                ('responsable_operativo', models.CharField(blank=True, max_length=255, null=True)),
                ('contratista', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('problemas_identificados', models.TextField(blank=True, null=True)),
                ('acciones_correctivas', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateField(blank=True, null=True)),
                ('problema_resuelve', models.TextField(blank=True, null=True)),
                ('solucion_ofrece', models.TextField(blank=True, null=True)),
                ('beneficio_ciudadania', models.TextField(blank=True, null=True)),
                ('dato_destacable', models.TextField(blank=True, null=True)),
                ('alineacion_gobierno', models.TextField(blank=True, null=True)),
                ('poblacion_perfil', models.TextField(blank=True, null=True)),
                ('relevancia_comunicacional', models.TextField(blank=True, null=True)),
                ('hitos_comunicacionales', models.TextField(blank=True, null=True)),
                ('mensajes_clave', models.TextField(blank=True, null=True)),
                ('estrategia_comunicacion', models.TextField(blank=True, null=True)),
                ('control_captura', models.TextField(blank=True, null=True)),
                ('control_notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
